server:
  port: 8083
  servlet:
    context-path: /dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sais?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    tomcat:
      initSQL: SET NAMES utf8mb4


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sais.entity

#showSql
logging:
  level:
    com:
      sais:
        mapper : debug

pageSize: 20
devName: BugAngel
content: "pageSize:${pageSize},devName:${devName}"

dev:
  name: 紫陌飞雪
  age: 26
  id: 365