mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sais.saisentity

#showSql
logging:
  level:
    com:
      sais:
        saismapper : debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
