mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sais.saisentity

#showSql
logging:
  level:
    com:
      sais:
        saismapper : debug

pagehelper:
  helper-dialect: mysql   #配置数据库
  reasonable: true  #pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  support-methods-arguments: true
