server:
  port: 8083
  servlet:
    session:
      timeout: 3000
#静态资源对外暴露的访问路径
########   windows   ############
file:
  uploadAccessPath: /upload/**
  uploadPath: E:/sais/upload/
  collegeImagesUploadPath: E:/sais/upload/college/images/
  microblogImagesUploadPath: E:/sais/upload/microblog/images/
  microblogHeadImagesPath: E:/sais/upload/microblog/images/head_image/

########   linux   ############
#file:
#  uploadPath: /home/upload/
#  collegeImagesUploadPath: /home/upload/college/images/
#  microblogImagesUploadPath: /home/upload/microblog/images/
#  microblogHeadImagesPath: /home/upload/microblog/images/head_image/
